By default, don't keep appending points to the end of a route
acteng/atip pull request #202
Opened 2023-05-30 15:11 UTC by dabreegster

See https://github.com/dabreegster/route_snapper/pull/30 for context. I haven't done UX testing with anyone, but I suspect this'll make the default experience much less weird. It's much easier to drag intermediate waypoints this way.

For people who want to change the default, combined with #201 would let them make the setting sticky.

2023-05-30 15:12 UTC, dabreegster commented
Preview at https://acteng.github.io/atip/extend_route/scheme.html?authority=Stoke-on-Trent

2023-05-31 11:15 UTC, Pete-Y-CS commented
> Preview at https://acteng.github.io/atip/extend_route/scheme.html?authority=Stoke-on-Trent

I just had a quick play and think this is really good but have a suggestion: it defaults to adding points to end, except when you 'edit geometry'.
Also maybe add points to start might be nice

2023-05-31 12:07 UTC, Pete-Y-CS commented
Looking at the code it looks like maybe my second request isn't available unless we control the route snapper package

2023-05-31 13:53 UTC, dabreegster commented
>  it defaults to adding points to end, except when you 'edit geometry'.

Wait, really? The "Add points to end" checkbox should be off by default and this should not happen.

> Also maybe a feature to add points to start might be nice

That could be nice. Even visually distinguishing the "last" point seems useful! These changes would go in https://github.com/dabreegster/route_snapper/, I'd say they're out of scope for Friday, but would like to think about how to implement them

2023-05-31 14:21 UTC, Pete-Y-CS commented
>  Wait, really? The "Add points to end" checkbox should be off by default and this should not happen.
I don't mean it does this I meant to say it might be a more expected way for it to behave: when making a new route it defaults to adding new waypoints, when editing a previous route it defaults to only allowing you to change existing waypoints

2023-05-31 14:31 UTC, dabreegster commented
> when making a new route it defaults to adding new waypoints, when editing a previous route it defaults to only allowing you to change existing waypoints

Ah, I see. This makes sense and may be a gentler transition for users used to the old behavior. Changed it to do that.

2023-05-31 14:32 UTC, dabreegster commented
It will make #201 confusing though -- if the user manually ticks the box, do we then override this automatic behavior? Maybe we just don't let them change that setting then?

2023-05-31 14:36 UTC, Pete-Y-CS commented
Yeah not sure what's best for this. Maybe we could have a default for each type of editing geometry: existing or new route, on a per user basis. I could also just see not having user preference here.

2023-06-01 13:17 UTC, Sparrow0hawk requested changes
I find the UX of this a little tricky, I find it too easy to delete a red waypoint when trying to grab it and drag it.  I found myself accidentally deleting red waypoints when trying to click and drag them and then having no way to undo it which was frustrating.

Is it feasible to:

- Change the interaction that triggers a waypoint deletion i.e. right mouse click?
- Make a click on a waypoint make it sticky to the cursor, so I don't have to drag I can just click and move it about (realise this would depend on changing waypoint deletion event)

2023-06-01 13:45 UTC, merged