Plumb along schema in URL
acteng/atip pull request #381
Opened 2023-11-01 13:36 UTC by dabreegster

Two quick fixes:
1) If you go the homepage with ?schema=foo, then we preserve that when you click an area. Otherwise our partner will have to manually add `schema=pipeline` in the near-future
2) Stop using .txt for downloaded files. This was something we did for better compatibility with SmartSurvey. Since we're not using a  new version of the sketch tool anytime soon, let's use .geojson, so people understand what the files are and they work with normal GIS tools

2023-11-01 13:44 UTC, dabreegster commented on tests/homepage.spec.ts
> -test("front page has welcome text", async ({ page }) => {
I think this was the original playwright test just to get started. It's not too useful now :)

2023-11-03 09:18 UTC, Pete-Y-CS requested changes
![image](https://github.com/acteng/atip/assets/133757676/25be4294-112c-41f3-adb7-bc43959f65ce)
Can we apply this to here too (`change area` button)

2023-11-03 09:54 UTC, dabreegster commented
Ooh good catch, thanks! OK to merge?

2023-11-03 09:56 UTC, Pete-Y-CS approved these changes

2023-11-03 09:57 UTC, merged