tweak how layers relating to specific ATE metrics are displayed
acteng/atip pull request #523
Opened 2024-10-15 15:47 UTC by Pete-Y-CS

2024-10-15 15:53 UTC, Pete-Y-CS commented
Looks like tests are failing due to playwright failing to install, guessing that's unrelated to this branch but will quickly check

2024-10-17 09:14 UTC, dabreegster requested changes

2024-10-17 09:14 UTC, dabreegster commented on src/lib/browse/layers/lines/PavementWidths.svelte
> +  let describeLimits = ["0-1.5m", "1.5-2m", "2-3m", "3+m"];
3+m   should be    >3m

2024-10-17 10:46 UTC, dabreegster approved these changes

2024-10-17 12:26 UTC, merged