begin to add a landing page
acteng/atip pull request #540
Opened 2024-11-13 15:00 UTC by Pete-Y-CS

Simple landing page with some descriptions of the tools

2024-11-13 16:57 UTC, dabreegster requested changes
Looks like a good start! Fixing the tests should be straightforward

2024-11-13 16:57 UTC, dabreegster commented on src/pages/LandingPage.svelte
> +        This feature allows you to sketch planned active travel schemes, or anything you might want to make a high level geographic sketch of. These can then be exported as geojson files to be shared
Wording is tough...

```suggestion
        Sketch active travel schemes at a high-level. This tool produces GeoJSON files that can be shared with others using this tool or imported into other GIS software.
```

2024-11-13 16:57 UTC, dabreegster commented on src/pages/LandingPage.svelte
> +    <h2>Browse Existing Sketches and Georgraphic Context:</h2>
```suggestion
    <h2>Browse existing sketches and geographic context:</h2>

```
Typo, and not sure about capitalizing every word -- can check the govuk style guide later

2024-11-13 16:57 UTC, dabreegster commented on src/pages/LandingPage.svelte
> +        Once you have made some sketches you can look at them in existing geographic context, by viewing the sketches alongside layers like bus routes, hospital locations, and authority boundaries.
```suggestion
        View scheme sketches alongside other contextual layers, like bus routes, hospital locations, and authority boundaries.

```

2024-11-14 09:04 UTC, dabreegster requested changes

2024-11-14 09:04 UTC, dabreegster commented on src/pages/LandingPage.svelte
> +    window.location.href = "/choose_area.html"
Please test your changes on the deployed version too! The links on https://acteng.github.io/atip/landing-page/ are broken; don't use absolute links, so it'll work in a variety of deployed environments. Just remove the / here and below

2024-11-14 09:04 UTC, dabreegster commented on choose_area.html
https://acteng.github.io/atip/landing-page/choose_area.html is missing, because you need to add it to `vite.config.ts`

2024-11-14 09:04 UTC, dabreegster commented on src/lib/common/Header.svelte
> +  <a href="/">
Use index.html, not absolute links

2024-11-14 09:04 UTC, dabreegster commented on src/pages/ChooseAreaHeader.svelte
> +  <a href="/">
Same

2024-11-14 09:04 UTC, dabreegster commented on tests/choosearea.spec.ts
nit: `choose_area.spec.ts`

2024-11-14 10:03 UTC, Pete-Y-CS commented on src/lib/common/Header.svelte
> +  <a href="/">
think these are resolved now.

2024-11-14 11:42 UTC, dabreegster approved these changes

2024-11-14 11:44 UTC, merged