Display route length, and backfill the missing property as needed
acteng/atip pull request #91
Opened 2023-03-20 13:17 UTC by dabreegster

Sarah had this small request. I've stuck it below the form, but styling suggestions welcome. (All of this is going to change soon, so maybe not important.)
![Screenshot from 2023-03-20 13-16-54](https://user-images.githubusercontent.com/1664407/226350135-9b670d3f-85f9-4fb1-afb8-7481911b57a2.png)

2023-03-20 13:22 UTC, dabreegster commented on components/EntireScheme.svelte
> +  function backfill(json) {
If/when this becomes more complicated, we can split out in some way. Robin mentioned this was also an annoying difference for analysis. Before we bulk analyze schemes, we should just run the same backfill process on all the inputs.

2023-03-20 13:22 UTC, dabreegster commented on tests/data/route.json
> +{
This is just something I sketched and saved really quickly. As we get more tests, we can either have a purpose-built input for each test, or maybe more realistically, make one or two inputs that cover a larger range of test cases.

2023-03-20 13:22 UTC, dabreegster commented on tests/savefiles.spec.js
> +  await page.locator("#load_geojson").setInputFiles({
See https://playwright.dev/docs/api/class-locator#locator-set-input-files for example. It's nice to pass in a local string, so we don't need to muck around with having a second copy of the input file with one tiny change

2023-03-20 20:23 UTC, Sparrow0hawk commented
I'm testing loading previous scheme files up in this PR and running into errors. 

Files i've tried:
- File without length_meters to test backfill, [West Yorkshire Combined Authority_testy test.txt](https://github.com/acteng/atip/files/11022703/West.Yorkshire.Combined.Authority_testy.test.txt)
- FIle with length_meters, [West Yorkshire Combined Authority_magic pie.txt](https://github.com/acteng/atip/files/11022706/West.Yorkshire.Combined.Authority_magic.pie.txt)

With each of these files on loading everything appears fine but I can't browse the intervention information and adding new interventions (I can still do this) isn't displayed on the sidebar. Exporting the geojson does now include these new features but I can't annotate them in the sidebar.

In the console I get the following error:

```
HMR][Svelte] Unrecoverable HMR error in <Form>: next update will trigger a full reload [proxy.js:15:11](http://localhost:5174/node_modules/svelte-hmr/runtime/proxy.js?v=e3641821)
    logError proxy.js:15
    Proxy<Form> proxy.js:380
    create_default_slot_1 InterventionList.svelte:93
    create_slot index.mjs:69
    create_fragment5 carbon-components-svelte.js:1509
    init index.mjs:2017
    AccordionItem carbon-components-svelte.js:1782
    create_each_block InterventionList.svelte:315
    update InterventionList.svelte:426
    update_slot_base index.mjs:98
    update carbon-components-svelte.js:1143
    update carbon-components-svelte.js:1274
    update index.mjs:1193
    flush index.mjs:1160
Uncaught (in promise) TypeError: x.round is not a function
    prettyPrintMeters Form.svelte:26
    create_if_block Form.svelte:50
    create_fragment Form.svelte:49
    init index.mjs:2017
    Form Form.svelte:530
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<Form> proxy.js:349
    create_default_slot_1 InterventionList.svelte:93
    create_slot index.mjs:69
    create_fragment5 carbon-components-svelte.js:1509
    init index.mjs:2017
    AccordionItem carbon-components-svelte.js:1782
    create_each_block InterventionList.svelte:315
    update InterventionList.svelte:426
    update_slot_base index.mjs:98
    update carbon-components-svelte.js:1143
    update carbon-components-svelte.js:1274
    update index.mjs:1193
    flush index.mjs:1160
```

2023-03-20 20:25 UTC, Sparrow0hawk requested changes

2023-03-20 20:25 UTC, Sparrow0hawk commented on components/Form.svelte
> +      return x.round() + " m";
See main thread for errors i'm getting this seem to point at this round call.

2023-03-22 10:35 UTC, dabreegster commented
Thanks so much for testing this and catching the problem! I had blind confidence in my manual and automated tests, but only hit the >1km path and didn't even think about it. I'm so used to a compiler telling me `x.round()` doesn't exist. :(   Maybe this is a strong push to switch to Typescript.

Everything looks correct to me now. I'm considering exhaustively testing <1km cases now, but it's maybe overkill. We could go back and really crank out a bunch of test cases if it becomes important.

2023-03-22 10:50 UTC, merged